export const LABELS = {
  waitGenImg: "Please wait while your image is generated",
  backToHomePage: "BACK TO HOME PAGE",
  congratulations: "CONGRATULATIONS!",
  sorry: "SORRY!",
  accReg: "Your account has been successfully registered.",
  createCase: "CREATE YOUR FIRST CASE",
  createYrCase: "CREATE YOUR CASE",
  createYrCaseNow: "CREATE YOUR CASE NOW",
  registerLogin: "Register/Login",
  logout: "Logout",
  welBack: "WELCOME BACK!",
  register: "Register",
  login: "login",
  name: "Name",
  email: "Email",
  password: "Password",
  newPassword: "New Password",
  confirmPassword: "Confirm Password",
  dontHaveAcc: "Don’t have an account yet?",
  alreadyHaveAcc: "Already have an account?",
  lostPwd: "Lost your password?",
  forgotPwd: "Forgot Your Password?",
  enterEmailResetLink: "Enter your email to receive a password reset link",
  resetPassword: "Reset Passwrod",
  sendEmail: "SEND EMAIL",
  backToLogin: "Back to login",

  myGallery: "My Gallery",
  aboutUs: "About us",
  credits: "Credits",
  freeCredits: "free credits",
  privacyPolicyCap: "PRIVACY POLICY",
  termsOfService: "TERMS OF SERVICE",
  shipping: "SHIPPING & RETURN POLICY",
  aboutUsCap: "ABOUT US",
  artcovrr: "Artcovrr",
  createMyAcc: "CREATE MY ACCOUNT",
  welToCaseCovrr: "Welcome to ArtCovrr",
  whereCutting: "Where cutting-edge technology meets personalized style.",
  foundedIn2023First:
    "Founded in 2023, we're a pioneering company committed to revolutionizing the tech accessories industry. Our mission is to provide uniquely designed, custom-generated AI cases that not only protect your devices but also reflect your individual personality and style.",
  foundedIn2023Second:
    "We're constantly pushing the boundaries of what's possible in the realm of tech accessories. As we continue to innovate and evolve, we're excited to bring you along on our journey, one custom case at a time.",
  howDoes: "HOW DOES IT WORK?",
  selectArt: "Select Art Style",
  personalize: "Personalize",
  chooseTry: "Buy or try again",
  chooseYr: "Choose your preferred style for the artwork",
  choosePhone: "Choose phone size, enter your text prompt(s)",
  addTo: "Add to cart or create variations",
  unleash: "UNLEASH YOUR INNER ARTIST WITH THE POWER OF AI",
  turnYour: "Turn Your Ideas into Artwork and Showcase It on Your iPhone",
  unleash2: "UNLEASH YOUR CREATIVITY WITH AI -",
  itHas: "IT HAS NEVER BEEN EASIER THAN THIS",
  only: "Only",
  freeShip: "Free Shipping",
  satisfaction: "100% Satisfaction Guarantee",
  faq: "FREQUENTLY ASKED QUESTIONS",
  faqQ1: "When will my order be delivered?",
  faqA1:
    "To find out the status of your order delivery, enter your shipment number from order confirmation email here.",
  chooseStyle: "Choose Style",
  willDescribe: "I’ll describe it myself",
  design1: "Art deco",
  design2: "Watercolor",
  design3: "Cyberpunk",
  design4: "Graphic print",
  design5: "Isometric anime",
  design6: "Pop art",
  design7: "Ukiyo-e",
  design8: "Op vintage",
  design9: "Cinematographic",
  design10: "Van Gogh",
  design11: "Abstract",
  noStyle: "No Style",
  selectIphone: "Select Phone Model",
  desArt: "Describe Art On Your Case",
  thingsYou: "Things You'd Like To Exclude (Optional)",
  genMyCase: "Generate My Case Design",
  desArtPlaceholder:
    "e.g. A fire-breathing dragon flying away from a burning city",
  thingsYouPlaceholder: "e.g. People, buildings, sky etc.",
  addToCart: "Add to cart",
  createVar: "Create Variations",
  loadMore: "Load more",
  youHave: "You haven’t generated any cases yet",
  accVerified: "Your account has successfully verified",
  remove: "Remove",
  add: "Add",
  item: "Item",
  items: "Items",
  myCart: "MY CART",
  currency: {
    euro: "€",
    dollar: "$",
  },
  total: "Total",
  subtotal: "Subtotal",
  delivery: "Delivery",
  vat: "VAT",
  included: "Included",
  checkout: "Checkout",
  addCredits: "Add Credits",
  getCredits: "Get Credits",
  timeUntil: "Time until",
  selectAmount: "Select the amount of credits you’d like to purchase.",
  ok: "OK",
};
